baseURL = 'http://jota-ele-ene.github.io/just-me-starter'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'just-me'

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]


[params]
  author = "John Doe"
  author_link = "#"
